timezone: Europe/Rome
permalink: pretty
repository: trasparente/mdr

# DEFAULTS
defaults:
  - scope:
      path: ''
    values:
      layout: default

# COLLECTIONS
collections:
  docs:
    title: Docs
    output: true
  posts:
    title: Posts